BEGIN
  EXECUTE IMMEDIATE 'CREATE USER DELIVERY_HANDLER IDENTIFIED BY "delivery" default tablespace users';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN
      RAISE;
    END IF;
END;
/

grant all privileges to DELIVERY_HANDLER;

ALTER SESSION SET CURRENT_SCHEMA = DELIVERY_HANDLER;
