BEGIN
    FOR t IN (
        SELECT table_name FROM user_tables
        WHERE table_name IN (
            'PAYMENT',
            'TRACKING_EVENT',
            'PARCEL_PARCEL_LOCKER',
            'COURIER',
            'PARCEL',
            'PARCEL_LOCKER',
            'DEPOT',
            'CUSTOMER'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/



CREATE TABLE customer (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR2(120) NOT NULL,
    email           VARCHAR2(254),
    phone           VARCHAR2(40),
    street_address  VARCHAR2(200),
    city            VARCHAR2(80),
    postal_code     VARCHAR2(20),
    country_code    CHAR(2) DEFAULT 'HU' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT customer_email_uk UNIQUE (email)
) tablespace users;

CREATE TABLE parcel (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_code       VARCHAR2(40) NOT NULL,
    sender_customer_id  NUMBER NOT NULL,
    receiver_customer_id NUMBER NOT NULL,

    weight_kg           NUMBER(6,3) CHECK (weight_kg >= 0),
    size_category       VARCHAR2(20) NOT NULL, -- S/M/L/XL
    declared_value_huf  NUMBER(12,0) CHECK (declared_value_huf >= 0),

    status              VARCHAR2(30) NOT NULL,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT parcel_tracking_uk UNIQUE (tracking_code),
    CONSTRAINT parcel_sender_fk FOREIGN KEY (sender_customer_id) REFERENCES customer(id),
    CONSTRAINT parcel_receiver_fk FOREIGN KEY (receiver_customer_id) REFERENCES customer(id),
    CONSTRAINT parcel_sender_receiver_chk CHECK (sender_customer_id <> receiver_customer_id),
    CONSTRAINT parcel_size_chk CHECK (size_category IN ('S','M','L','XL'))
) tablespace users;

CREATE TABLE parcel_locker (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locker_code     VARCHAR2(30) NOT NULL,
    name            VARCHAR2(120) NOT NULL,
    street_address  VARCHAR2(200) NOT NULL,
    city            VARCHAR2(80) NOT NULL,
    postal_code     VARCHAR2(20),
    country_code    CHAR(2) DEFAULT 'HU' NOT NULL,
    latitude        NUMBER(9,6),
    longitude       NUMBER(9,6),
    is_active       CHAR(1) DEFAULT 'Y' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT parcel_locker_code_uk UNIQUE (locker_code),
    CONSTRAINT parcel_locker_active_chk CHECK (is_active IN ('Y','N'))
) tablespace users;


CREATE TABLE parcel_parcel_locker (
    id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id            NUMBER NOT NULL,
    parcel_locker_id     NUMBER NOT NULL,

    placed_at            TIMESTAMP NOT NULL,
    removed_at           TIMESTAMP,
    operation            VARCHAR2(20) NOT NULL,
    access_code_hash     VARCHAR2(200), 

    CONSTRAINT ppl_parcel_fk FOREIGN KEY (parcel_id) REFERENCES parcel(id),
    CONSTRAINT ppl_locker_fk FOREIGN KEY (parcel_locker_id) REFERENCES parcel_locker(id),
    CONSTRAINT ppl_op_chk CHECK (operation IN ('DROPOFF','TRANSFER_IN','PICKUP','RETURN_DROP')),
    CONSTRAINT ppl_removed_after_placed_chk CHECK (removed_at IS NULL OR removed_at >= placed_at)
) tablespace users;


CREATE INDEX ppl_parcel_time_ix ON parcel_parcel_locker (parcel_id, placed_at DESC);


CREATE TABLE depot (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    depot_code      VARCHAR2(30) NOT NULL,
    name            VARCHAR2(120) NOT NULL,
    city            VARCHAR2(80) NOT NULL,
    street_address  VARCHAR2(200),
    is_active       CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT depot_code_uk UNIQUE (depot_code),
    CONSTRAINT depot_active_chk CHECK (is_active IN ('Y','N'))
) tablespace users;


ALTER TABLE parcel_locker ADD depot_id NUMBER;
ALTER TABLE parcel_locker
  ADD CONSTRAINT parcel_locker_depot_fk
  FOREIGN KEY (depot_id) REFERENCES depot(id);


CREATE TABLE courier (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    courier_code    VARCHAR2(30) NOT NULL,
    full_name       VARCHAR2(120) NOT NULL,
    phone           VARCHAR2(40),
    is_active       CHAR(1) DEFAULT 'Y' NOT NULL,
    hired_at        DATE,
    CONSTRAINT courier_code_uk UNIQUE (courier_code),
    CONSTRAINT courier_active_chk CHECK (is_active IN ('Y','N'))
) tablespace users;


CREATE TABLE tracking_event (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id        NUMBER NOT NULL,
    event_time       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    event_type       VARCHAR2(30) NOT NULL, 
    depot_id         NUMBER,
    parcel_locker_id NUMBER,
    courier_id       NUMBER,
    notes            VARCHAR2(400),

    CONSTRAINT te_parcel_fk FOREIGN KEY (parcel_id) REFERENCES parcel(id),
    CONSTRAINT te_depot_fk FOREIGN KEY (depot_id) REFERENCES depot(id),
    CONSTRAINT te_locker_fk FOREIGN KEY (parcel_locker_id) REFERENCES parcel_locker(id),
    CONSTRAINT te_courier_fk FOREIGN KEY (courier_id) REFERENCES courier(id),

    CONSTRAINT te_type_chk CHECK (
        event_type IN (
            'CREATED',
            'SCANNED_AT_DEPOT',
            'LOADED_FOR_DELIVERY',
            'ARRIVED_LOCKER',
            'PICKED_UP',
            'DELIVERED',
            'RETURNED'
        )
    )
) tablespace users;

CREATE INDEX te_parcel_time_ix ON tracking_event (parcel_id, event_time DESC);

CREATE TABLE payment (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id        NUMBER NOT NULL,
    amount_huf       NUMBER(12,0) NOT NULL CHECK (amount_huf >= 0),
    method           VARCHAR2(20) NOT NULL,
    paid_at          TIMESTAMP,
    status           VARCHAR2(20) NOT NULL,

    CONSTRAINT payment_parcel_fk FOREIGN KEY (parcel_id) REFERENCES parcel(id),
    CONSTRAINT payment_method_chk CHECK (method IN ('CARD','TRANSFER','COD')),
    CONSTRAINT payment_status_chk CHECK (status IN ('PENDING','PAID','FAILED','REFUNDED'))
) tablespace users;

CREATE INDEX payment_parcel_ix ON payment (parcel_id);
